### ISSUE TITLE
SRS Review: Some user responsibility could become software responsibility

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#10]
Some user responsibilities could be easily removed or checked. For example, your software interface could be designed in a way that allows users to simply enter a quadratic function, relieving them of that responsibility. Additionally, determining whether a function is positive semidefinite (PSD) or not could be handled within the implementation. For instance, if you're using Numpy, you could check like this:
`np.all(np.linalg.eigvals(x) > 0)
`

**Comment by FasilCheema** [comment]
This is a good point that is natural to our problem. However, after discussion with Dr Smith if the check for the validity of the input is as, or more, difficult than  the problem we are trying to solve; we may choose to leave that as a user responsibility. Even though it may be a single function call it is still as hard of a problem computationally to verify a matrix's PSD-ness as it is to find roots for a quadratic form expression. For this reason, we have opted to leave this as a user responsibility.
