### ISSUE TITLE
SRS Review: Dimension=6, is it needed as a system constraint?

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#12]
Regarding section 3.3, I'm unsure if restricting demotion to six is a system constraint or an assumption. How did you arrive at the number six? If it's related to the system requirement, could it be a constant in your software that can be adjusted as needed?

**Comment by FasilCheema** [comment]
The design decision of 6 was chosen to have the library output an answer in a `reasonable' amount of time. This takes into account various devices it may be run on. For most laptops I would like to avoid runtimes exceeding an hour and hence define this constant to be 6. It is a constant in the constants module named MAX_DIM and can easily be modified there and allow users to go beyond. For the sake of keeping the problem feasible on most standard devices we chose this number but it can be exceeded.
