### ISSUE TITLE
SRS: Relation of inputs and outputs in the theoretical model

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#13]
In the theoretical model, such as TM:CON, it's better to specify the types of variables and the input-output relationships of the functions. For example, specifying that lambda is in R, x1 and x2 are in R^n, and f: R^n -> R.

**Comment by FasilCheema** [comment]
Type information is now explicitly stated for every instance of parameter or variables in the SRS documentation.
