### ISSUE TITLE
VnV Review: Ensure Comprehensive Test Coverage for All Requirements

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#14]
It's essential to ensure that all requirements are thoroughly tested to achieve comprehensive test coverage. Since there are 5 requirements listed, each should have at least one corresponding test. This will help validate the functionality of the software against each requirement. Right now you just covered R1 and R2.

**Comment by FasilCheema** [comment]
I have added further test in the final VnV plan and report. Now all requirements are covered.
