### ISSUE TITLE
VnV Review: Specify Exact Input Parameters for Testing Input Features

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#16]
While section 4.1.2 effectively describes the input feature, it would be beneficial to specify the exact values of A and b used for testing purposes. Additionally, testing every combination of dimensions may be unnecessary and could be streamlined for efficiency.

**Comment by FasilCheema** [comment]
This has been modified for the final VnV plan and report. We did not use matrix form but opted to choose the python line to aid in reproduciblity of what specific instances of A and b and other inputs will be used. See VnV  plan [https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/VnVPlan/VnVPlan.pdf](url) and [https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/VnVReport/VnVReport.pdf](url)
