### ISSUE TITLE
VnV Review: Consider Secondary Review Test for Indistinguishable Results

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#17]
For the implementation of DFP, FRCG, and BFGS, if the final results are identical and indistinguishable, consider adding a secondary review test to manually verify the results. This additional step will ensure confidence in the correctness of the implementation. You could add this as manual testing and reviewing.

**Comment by FasilCheema** [comment]
Depending on the method, number of steps, being implemented it is not guaranteed that the methods will have identical results. For instance if a matrix is PSD and has a valid solution FRCG will find the solution for a quadratic form (our case) in at most 2 steps. The other methods do not come with this guarantee and hence (as seen in practice) do not result in the same solutions. That being said for tests we have solutions from a well-trusted textbook. This will act as a natural method to test our algorithms.
