### ISSUE TITLE
MG MIS review

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#19]
Hi Dr Smith can you review my design documents? 

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftArchitecture/MG.pdf](url)
[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftDetailedDes/MIS.pdf](url)

**Comment by smiths** [comment]
[FasilMG.pdf - PDF Expert.pdf](https://github.com/FasilCheema/OptimizationLibrary/files/14846222/FasilMG.pdf.-.PDF.Expert.pdf)
[FasilMIS.pdf - PDF Expert.pdf](https://github.com/FasilCheema/OptimizationLibrary/files/14846223/FasilMIS.pdf.-.PDF.Expert.pdf)
