### ISSUE TITLE
Review MG/MIS (main reviewer)

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#20]
Hi Morteza! Could you please review my MG/MIS. Thank you!

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftArchitecture/MG.pdf](https://github.com/FasilCheema/OptimizationLibrary/issues/url)

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftDetailedDes/MIS.pdf](https://github.com/FasilCheema/OptimizationLibrary/issues/url)

**Comment by morteza-im** [comment]
Hi @FasilCheema,

I've had a chance to review your designs, and overall, it's really good.
Here are my reviews:
#27, #28, #29, #30, #31

Thanks,
Morteza
