### ISSUE TITLE
MG/MIS Review 

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#21]
Hi Valerie, 

please review my MG/MIS. Thank you!

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftArchitecture/MG.pdf](url)

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/Design/SoftArchitecture/MIS.pdf](url)

**Comment by vgvreug** [comment]
Review complete. Please see issues #22 #23 #24 #25 #26
