### ISSUE TITLE
MG+MIS: misc small issues

### ISSUE THREAD

**Issue by vgvreug** [FasilCheema/OptimizationLibrary#26]
- [ ] MG 2.1: description of OptLib wasn't changed from default
- [ ] MG AC1+AC3: seems redundant to have "maximum" and "upper bound"
- [ ] MG UC1: seems redundant to have "will not change" when the section is "Unlikely Changes"
- [ ] MG 10: The comment in parentheses probably isn't necessary. It should either be deleted or rewritten to be a sentence explaining why there is no user interface
- [ ] MIS: half of the bottom line of the revision history table is missing
- [ ] MIS 6.4.4: item 2 references a "Input Parameters Module", I assume this is meant to be the Input Verification Module

**Comment by FasilCheema** [comment]
T1: Changed description of OptLib 
T2: opted to keep this just for clarification but have removed several instances to help readability. 
T3: Removed
T4: Have added further clarification, explaining the library interface does not have a user interface
T5: Have added this missing content. 
T6: Have fixed this issue with the proper naming
