### ISSUE TITLE
Reevaluate Module Type for Main Module (M2)

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#27]
The current classification of the Main Module (M2) as a "Library" may not accurately represent its functionality. While it serves as an entry point for users to access functions and controls program execution, "Library" typically refers to an external resource. Considering its role within the system, "Abstract Object" or a similar classification might be more appropriate.

**Comment by FasilCheema** [comment]
The main module has been removed as it does not suit the specification of a function library. For this reason, we have opted to use an OptLib library that acts as the entry point into the library.
