### ISSUE TITLE
SRS 

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#3]
I have uploaded my SRS  :) 

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/SRS/SRS.pdf](url)

**Comment by smiths** [comment]
The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

[FasilCheema_SRS.pdf](https://github.com/FasilCheema/OptimizationLibrary/files/14390331/FasilCheema_SRS.pdf)
