### ISSUE TITLE
Update MIS of Input Verification Module

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#31]
What is the type of _params_ in MIS for the Input Verification Module?
The exception part for this module is empty. You could consider implementing error messages within the access routines as exceptions for better error management and system robustness.

**Comment by FasilCheema** [comment]
params is a record that contains multiple variables that stay constant throughout the optimization problem. This variable acts to be passed around allowing modules to easily have access to relevant values in one location. I have added information that should clarify this in the documentation (MIS). I agree with your error handling ideology however as the initial input verification checks for errors we assume in the rest of the modules that the inputs are valid and hence no additional checks are required.
