### ISSUE TITLE
VnV Review

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#6]
Hi I would really appreciate it if you could review my VnV :) 

[https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/VnVPlan/VnVPlan.pdf](url)

**Comment by smiths** [comment]
[Fasil_VnVPlan.pdf](https://github.com/FasilCheema/OptimizationLibrary/files/14566772/Fasil_VnVPlan.pdf)
