### ISSUE TITLE
VnV Plan Review

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#7]
Hi, kindly review my system VnV plan :) [https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/VnVPlan/VnVPlan.pdf](url)

**Comment by morteza-im** [comment]
Hi @FasilCheema,
I enjoyed your VnV Plan. Here are my reviews:
#14, #15, #16, #17, #18
