### ISSUE TITLE
VnV Plan Review 

### ISSUE THREAD

**Issue by FasilCheema** [FasilCheema/OptimizationLibrary#8]
Hi please kindly review my system VnV plan :) [https://github.com/FasilCheema/OptimizationLibrary/blob/main/docs/VnVPlan/VnVPlan.pdf](url)

**Comment by lele0007** [comment]
I write some comments on the document.
[VnVPlan.pdf](https://github.com/FasilCheema/OptimizationLibrary/files/14368435/VnVPlan.pdf)

**Comment by FasilCheema** [comment]
Thank you Xinyu, I have added all relevant changes into my documentation in my new modified VnV plan.
