### ISSUE TITLE
SRS Review: Specify Algorithms like DFP and BFGS in instance model.

### ISSUE THREAD

**Issue by morteza-im** [FasilCheema/OptimizationLibrary#9]
I anticipated that in the instance models, you would explain the 'David-Fletcher-Powell (DFP), Fletcher-Reeves Conjugate Gradient, and the Broyden-Fletcher-Goldfarb-Shanno (BFGS) algorithms' that you mentioned at the beginning of the document. However, the instance models remained at a high level and did not delve into this level of detail.

**Comment by FasilCheema** [comment]
These algorithms are more complex algorithms and would not fit into defining them as instance models of higher-level theoretical models. I have included Quasi-Newton and Conjugate Gradient methods as instance models but for the sake of abstraction I have opted against showing all specific details of these algorithms here. This additional detail may be too specific for the SRS. They can be found in the MIS.
